```plantuml
@startuml Account Management

skinparam backgroundColor HotPink

    abstract class User{
        -firstName
        -lastName
        -userName
        -password
        -role
    }

    class Administrator extends User{

    }

    class ServiceProvider extends User{

    }
    class Client extends User{

    }

    class Service{
      -role
      -price
      -name
    }

    class ProviderProfile{
      -companyName
      -address
      -phoneNumber
      -generalDescription
      -licensed
    }

    ServiceProvider "1" -- "1" ProviderProfile: > has a
    ServiceProviderProfile "1" -- "*" Service: > provides a
@enduml
```
